# Generated by Django 4.0.2 on 2022-02-10 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='RecipeTagMap',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag',
                                         verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='UserFavouriteRecipeMap',
        ),
        migrations.AddField(
            model_name='recipe',
            name='followers',
            field=models.ManyToManyField(related_name='favourite_recipes',
                                         to=settings.AUTH_USER_MODEL,
                                         verbose_name='Followers'),
        ),
    ]
