# Generated by Django 4.0.2 on 2022-02-10 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
        migrations.DeleteModel(
            name='FollowerFollowingMap',
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL,
                                         verbose_name='Followings',
                                         related_name='followers'),
        ),
    ]
