# Generated by Django 4.0.2 on 2022-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='ShoppingCartRecipeMap',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe',
                                         verbose_name='Recipes',
                                         related_name='shopping_carts',
                                         ),
        ),
    ]
